spring:
  application:
    name: agent
  config:
    import: optional:configserver:http://localhost:8888



#spring:
#  application:
#    name: Agent
#
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/sicet
#    username: root
#    password: pass@word1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#  jpa:
#    generate-ddl: true
#    properties:
#      hibernate:
#      ddl-auto: update
#      show-sql: true
#
#server:
#  port: 9099
