eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: agency
          uri: http://localhost:9099
          predicates:
            - Path=/agency/**

        - id: agent
          uri: http://localhost:9101
          predicates:
            - Path=/agent/**

        - id: worker
          uri: http://localhost:2008
          predicates:
            - Path=/worker/**

        - id: review
          uri: http://localhost:2009
          predicates:
            - Path=/review/**

