eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: review
  data:
    mongodb:
      host: localhost
      port: 27017
      database: myapp

server:
  port: 2009

